### ISSUE TITLE
Filter Courses and Finals Data

### ISSUE THREAD

**Issue by vvp002** [vvp002/campus-mobile#12]
Parse the test schedule data into 2 parts:
1. just including a student's courses
2. just including a student's finals

so that they can passed into the daily/full schedule and finals cards respectively.

**Comment by slmnliu** [comment]
Adjusted getData function in scheduleData.js to aggregate ALL schedule_data. 
Added two separate functions for parsing Finals data and Class data (including discussions) into getFinals and getClasses respectively.
Change is reflected in ScheduleCard.js by changing getData to getClasses, because getData used to function as getClasses.
