### ISSUE TITLE
Add Time-Based Functionality to Finals Schedule Card

### ISSUE THREAD

**Issue by slmnliu** [vvp002/campus-mobile#21]
**User Story:**
As a student, I want to my most upcoming classes based on the current time so that I can keep track of my schedule better.

**Comment by slmnliu** [comment]
**Scenario:**
**_Given_** the user is logged in
_And_ the user is a student
_And_ the user is currently enrolled in classes
_And_ the user has Finals within a week (i.e. it is currently week 10)

**_When_** the Home View appears

**_Then_** ensure the Finals Schedule Card is displaying the user's upcoming Finals in chronological order
_And_ ensure that the Finals Card only appears when finals are prominent (i.e. it is Week 10 and beyond)

**Comment by vvp002** [comment]
With time based functionality, Finals Card would only chronologically display upcoming finals, rather than a complete list of all of them. So added logic to check current time/day and update the Finals Card during Finals Week.

Tested and working to display only upcoming finals. Need further discussion on what to display/do with no finals left. So commenting out time based logic and revert to full Finals List

**Comment by vvp002** [comment]
Closing issue, since time based functionality for finals was added. Just not being used.
